### ISSUE TITLE
OpenTitus [OPENTITUS]

### ISSUE THREAD

**Issue by IllusionMan1212** [Vita3K/homebrew-compatibility#224] opened 2018-04-27 20:39 UTC
# Homebrew summary
- VitaDB: https://vitadb.rinnegatamante.it/#/info/345
- Homebrew version: v1.0

# Vita3K summary
- Version: v0.1
- Build number: 187
- Commit hash: https://github.com/vita3k/vita3k/commit/4081bd1

# Test environment summary
- Tested by: IllusionMan1212
- OS: Windows 10 Pro
- CPU: AMD Ryzen 5 1600
- GPU: NVIDIA GTX 1050Ti
- RAM: 8 GB

# Issues
Crashes after intro screen

# Screenshots
![image](https://user-images.githubusercontent.com/36709480/39384026-af88a62c-4a6b-11e8-9622-d1402921b19e.png)

# Log
[vita3k.log](https://github.com/Vita3K/homebrew-compatibility/files/1956594/vita3k.log)

**Comment by nishinji** [comment] 2024-07-17 01:54
duplicate of https://github.com/Vita3K/homebrew-compatibility/issues/85

**Closed** 2024-07-17 01:55 UTC
Labels: crash
