### ISSUE TITLE
VitaShell v.1.78

### ISSUE THREAD

**Issue by aakh1361** [Vita3K/homebrew-compatibility#152] opened 2018-04-17 01:22 UTC
# Homebrew summary
- VitaDB: <http://vitadb.rinnegatamante.it/#/info/21>
- Homebrew version: v1.78

# Vita3K summary
- Version: v0.1
- Build number: 132
- Commit hash: db144745

# Test environment summary
- Tested by: AAKH1361
- OS: Windows 10
- CPU: Intel E5742
- GPU: NVIDIA GTX 780 Ti
- RAM: 16 GB

# Issues
ingame
Show Text Problem
Unknown partition sdstor0:int-lp-ign-userext used. Report this to developers!

# Screenshots
![](https://?)
![image](https://user-images.githubusercontent.com/25039098/38843007-57d3af60-4202-11e8-9929-aabdb36e684b.png)

![image](https://user-images.githubusercontent.com/25039098/38843021-66f9b71e-4202-11e8-9473-18c4f16ac4af.png)

![image](https://user-images.githubusercontent.com/25039098/38843046-8a5adbc0-4202-11e8-9402-30c16cd61f79.png)

# Recommended labels
Log File 
[vita3k.zip](https://github.com/Vita3K/homebrew-compatibility/files/1917821/vita3k.zip)

**Comment by IllusionMan1212** [comment] 2018-04-17 15:52
Duplicate of #30 
also old version

**Closed by IllusionMan1212** 2018-04-17 15:52 UTC
